package model;
// Generated Jan 8, 2016 7:45:08 PM by Hibernate Tools 4.3.1


import java.sql.Time;
import java.util.Date;

/**
 * Consultations generated by hbm2java
 */
public class Consultations  implements java.io.Serializable {


     private Integer id;
     private Kids kids;
     private Pediatricians pediatricians;
     private Date visitDate;
     private Time startTime;
     private Time endTime;
     private String reason;
     private String prescription;
     private String comments;

    public Consultations() {
    }

	
    public Consultations(Kids kids, Pediatricians pediatricians) {
        this.kids = kids;
        this.pediatricians = pediatricians;
    }
    public Consultations(Kids kids, Pediatricians pediatricians, Date visitDate, 
            Time startTime, Time endTime, String reason, String prescription, String comments) {
       this.kids = kids;
       this.pediatricians = pediatricians;
       this.visitDate = visitDate;
       this.startTime = startTime;
       this.endTime = endTime;
       this.reason = reason;
       this.prescription = prescription;
       this.comments = comments;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Kids getKids() {
        return this.kids;
    }
    
    public void setKids(Kids kids) {
        this.kids = kids;
    }
    public Pediatricians getPediatricians() {
        return this.pediatricians;
    }
    
    public void setPediatricians(Pediatricians pediatricians) {
        this.pediatricians = pediatricians;
    }
    
    public Date getVisitDate() {
        return this.visitDate;
    }
    
    public void setVisitDate(Date visitDate) {
        this.visitDate = visitDate;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public String getPrescription() {
        return this.prescription;
    }
    
    public void setPrescription(String prescription) {
        this.prescription = prescription;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


