package model;
// Generated Jan 8, 2016 7:45:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Kids generated by hbm2java
 */
public class Kids  implements java.io.Serializable {


     private Integer id;
     private Parents parents;
     private String name;
     private Date birthDate;
     private Set consultationses = new HashSet(0);

    public Kids() {
    }

	
    public Kids(Parents parents) {
        this.parents = parents;
    }
    public Kids(Parents parents, String name, Date birthDate, Set consultationses) {
       this.parents = parents;
       this.name = name;
       this.birthDate = birthDate;
       this.consultationses = consultationses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Parents getParents() {
        return this.parents;
    }
    
    public void setParents(Parents parents) {
        this.parents = parents;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public Set getConsultationses() {
        return this.consultationses;
    }
    
    public void setConsultationses(Set consultationses) {
        this.consultationses = consultationses;
    }

    public void addConsultation(Consultations consultation) {
        this.consultationses.add(consultation);
    }



}


