package model;
// Generated Jan 6, 2016 1:22:02 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.NotEmpty;
import javax.validation.constraints.Size;
import org.hibernate.validator.constraints.Email;

/**
 * Parents generated by hbm2java
 */
public class Parents implements java.io.Serializable {

    private Integer id;
    private String firstName;
    private String lastName;
    private String address;
    private String city;
    
    @Size(min=10,max=10, message="Your telephone number must be exactly 10 digits!")
    //@Pattern(regexp="(^$|[0-9])", message="Your telephone must contain only digits[0-9]!")
    private String telephone;
    
    @Email(message="Please provide a valid email address!")
    private String email;

    @NotEmpty(message = "Please enter your password.")
    @Size(min = 6, max = 15, message = "Your password must be between 6 and 15 characters!")
    private String password;
    private Set kidses = new HashSet(0);

    public Parents() {
    }

    public Parents(String email, String password) {
        this.email = email;
        this.password = password;
    }

    public Parents(String firstName, String lastName, String address, String city, String telephone, String email, String password, Set kidses) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.city = city;
        this.telephone = telephone;
        this.email = email;
        this.password = password;
        this.kidses = kidses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getKidses() {
        return this.kidses;
    }

    public void setKidses(Set kidses) {
        this.kidses = kidses;
    }

    public void addKid(Kids kid) {
        this.kidses.add(kid);
    }

}
