package model;
// Generated Jan 6, 2016 8:37:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Specialties generated by hbm2java
 */
public class Specialties  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set pediatricianses = new HashSet(0);

    public Specialties() {
    }

    public Specialties(String name, Set pediatricianses) {
       this.name = name;
       this.pediatricianses = pediatricianses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getPediatricianses() {
        return this.pediatricianses;
    }
    
    public void setPediatricianses(Set pediatricianses) {
        this.pediatricianses = pediatricianses;
    }
    
    public void addPediatrician(Pediatricians ped){
        this.pediatricianses.add(ped);
    }
    
    public void removePediatrician(Pediatricians ped){
        this.pediatricianses.remove(ped);
    }




}


