package model;
// Generated Jan 1, 2016 6:29:25 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.FetchType;
import javax.persistence.Id;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Entity;
import org.hibernate.annotations.Table;
import org.hibernate.mapping.OneToMany;
import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;


/**
 * Users generated by hbm2java
 */
@Indexed
public class Users implements java.io.Serializable {

    @Id
    @Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
    //@DocumentId(name="username")
    private String username;
    private String password;
    private byte enabled;

    private Set userRoleses = new HashSet(0);

    public Users() {
    }

    public Users(String username, String password, byte enabled) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
    }

    public Users(String username, String password, byte enabled, Set userRoleses) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
        this.userRoleses = userRoleses;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public byte getEnabled() {
        return this.enabled;
    }

    public void setEnabled(byte enabled) {
        this.enabled = enabled;
    }

    public Set getUserRoleses() {
        return this.userRoleses;
    }

    public void setUserRoleses(Set userRoleses) {
        this.userRoleses = userRoleses;
    }

}
